# Generated by Django 6.0.6 on 2026-07-06 00:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('legs', 'Legs'), ('core', 'Core'), ('cardio', 'Cardio'), ('full_body', 'Full Body'), ('mobility', 'Mobility')], default='full_body', max_length=20)),
                ('equipment', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'exercise',
                'verbose_name_plural': 'exercises',
                'db_table': 'exercises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'db_table': 'programs',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('recurrence_type', models.CharField(choices=[('weekly', 'Specific days of the week'), ('interval', 'Every N days')], default='weekly', max_length=20)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('anchor_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='workouts.program')),
            ],
            options={
                'verbose_name': 'routine',
                'verbose_name_plural': 'routines',
                'db_table': 'routines',
                'ordering': ['program', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('target_sets', models.PositiveIntegerField(default=3)),
                ('target_reps_min', models.PositiveIntegerField(default=8)),
                ('target_reps_max', models.PositiveIntegerField(blank=True, null=True)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routine_exercises', to='workouts.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.routine')),
            ],
            options={
                'verbose_name': 'routine exercise',
                'verbose_name_plural': 'routine exercises',
                'db_table': 'routine_exercises',
                'ordering': ['routine', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.program')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='workouts.routine')),
            ],
            options={
                'verbose_name': 'workout session',
                'verbose_name_plural': 'workout sessions',
                'db_table': 'workout_sessions',
                'ordering': ['-date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('set_number', models.PositiveIntegerField(default=1)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_entries', to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_entries', to='workouts.workoutsession')),
            ],
            options={
                'verbose_name': 'set entry',
                'verbose_name_plural': 'set entries',
                'db_table': 'set_entries',
                'ordering': ['session', 'order', 'set_number'],
            },
        ),
    ]
